### ISSUE TITLE
Differnt sc reference for different bulk

### ISSUE THREAD

**Issue by yujias424** [WWXkenmo/ENIGMA#13]
Hi Weixu!

Thank you for presenting this nice package. I am wondering whether it is a better way to use the single cell data from disease status to deconvolute the bulk from disease? For example, say we have 10 healthy bulk sample and 10 T2D bulk sample. At the same time, we may have 5 healthy single-cell data and 5 T2D single cell data. I am wondering whether it is better for us to use the T2D sc data to deconvolute the T2D bulk sample instead of using healthy sc data to deconvolute both T2D and healthy sample.

Thanks!

Best Regards,
Larry

**Comment by WWXkenmo** [comment]
Hey Larry

Sure, certainly if you have a better reference, you could deconvolute samples better. 

The reason why I use health sample to deconvolute both health and disease because I expect to use ENIGMA find some cell type specific disease features. And the "differences" need to be learned from algorithm itself rather than from samples. So I use the same reference for both health and disease just for method performance validation. Of course you can use T2D single cell data to deconvolute the T2D bulk sample.

Let me know if you have further issues.

Cheers!
Weixu

**Comment by WWXkenmo** [comment]
Close it due to there has no further response
