### ISSUE TITLE
get_cell_proportion taking forever to run

### ISSUE THREAD

**Issue by ankur26197-acog** [WWXkenmo/ENIGMA#9]
Hi,
I am running the code available [here](https://github.com/WWXkenmo/ENIGMA/blob/master/vignettes/A-simple-guide-of-ENIGMA.pdf) stepwise(except step 2 because my ref_type is single_cell). I am using same datasets as well. I have loaded reference in Seurat object. Running `get_cell_proportion` is taking forever. I wanted to ask if it did happened for you too. I am using `RLR` since the document says that `CIBERSORT` takes longer time.

Thank you.

**Comment by WWXkenmo** [comment]
Hey,

Have you run the batch_correct step, because when your ref_type is single cell, you need to run S-mode to get the reference profile matrix (n by k), in which k = number of cell types & n = number of samples. one way to perform quickly check is to look the dimension of `object@ref`, and you would see that without batch_correct step, the ref matrix is simply single cell gene expression matrix (n by m) m = number of cells. Which definitely take forever to run

Best,
Ken

**Comment by ankur26197-acog** [comment]
Hi,
Thanks for the reply. It worked after applying batch correction. However the document quotes `When the ref_type = “single_cell”, ENIGMA would automatically use S-mode to correct batch effects.`. My ref_type is single_cell so I wasn't explicitly doing it.

**Comment by WWXkenmo** [comment]
Hey, 

Now I understand the where lead to the misunderstanding, I would fix this later

Best,
Ken
